#!/bin/bash
# From the EasyBuild module installation log file read the source file path and check the timestamp

DIR=/apps/software/standard

function check {
    case $1 in 
        core) d=4;;
        compiler) d=6;;
        mpi) d=8;;
    esac
    find $1 -maxdepth $d -name '*.log' -exec sh -c "f=\$(awk '/Found file/ {print \$NF}' {}) && \
    [ -f \"\$f\" ] && ls -l \$f || echo \$f not found" \;
}

cd $DIR

if [ $# -eq 1 ]; then
    check $1
    exit
fi

for i in core compiler mpi; do
    echo [$i]
    check $i
    echo
done
