#!/bin/bash
# look for potentially incomplete installations in apps
# criterion:
# - missing *.eb file
#
# Ruoshi Sun
# 2020-02-18

APPDIR=/sfs/applications

if [ $# -eq 0 ]; then
    echo "Usage: `basename $0` YYYYMM [...]"
    exit 1
fi

YYYYMMs=$@

function search_eb {
    search=$1
    incomplete=()
    for i in `echo "$search"`; do
        if [ -d $i -a ! -e $i/easybuild/*.eb ]; then
            incomplete+=( "$i" )
        fi
    done
}

for YYYYMM in $YYYYMMs; do
    echo "[$YYYYMM]"
    for CATEGORY in core compiler mpi toolchains container; do
        cd $APPDIR/$YYYYMM/software/standard/$CATEGORY

        case $CATEGORY in
        core|toolchains)
            search="*/*"
            N=`find -maxdepth 2 -mindepth 2 -type d | wc -l`
            ;;
        compiler|container)
            search="*/*/*/*"
            N=`find -maxdepth 4 -mindepth 4 -type d | wc -l`
            ;;
        mpi)
            search="*/*/*/*/*/*"
            N=`find -maxdepth 6 -mindepth 6 -type d | wc -l`
            ;;
        esac

        search_eb "$search"
        
# number of incomplete installations
        n=${#incomplete[@]}

        echo "$CATEGORY (${n}/${N})"
        if [ $n -gt 0 ]; then
            printf '    %s\n' "${incomplete[@]}"
        fi
    done
    echo
done
