#!/bin/bash
# look for potentially incomplete installations in apps
# criterion:
# - missing *.eb file in easybuild/ or easybuild/reprod
#
# Ruoshi Sun
# 2020-02-18

APPDIR=/sfs/applications

if [ $# -eq 0 ]; then
    echo "Usage: `basename $0` YYYYMM [...]"
    exit 1
fi

YYYYMMs=$@

function search_eb {
    CATEGORY=$1
    DEPTH=$2
    incomplete=()

    cd $APPDIR/$YYYYMM/software/standard/$CATEGORY
    echo "$CATEGORY:"
    find -maxdepth $DEPTH -mindepth $DEPTH -type d '!' -exec sh -c 'ls -1 "{}"/easybuild 2>/dev/null|egrep -iq "^*\.eb$"' ';' -print
}

for YYYYMM in $YYYYMMs; do
    echo "[$YYYYMM]"

    search_eb core       2
    search_eb compiler   4
    search_eb mpi        6
    search_eb toolchains 2
    search_eb container  4

    echo
done
