#!/bin/bash
# test module load for the entire apps stack
# Ruoshi Sun
# 2020-11-17

if [ $# -ne 1 ]; then
    echo "Usage: `basename $0` CATEGORY"
    echo "    CATEGORY = core|toolchains|compiler|mpi|container|vendor|all"
    echo "Since the modules need to be loaded, you cannot run this script for other YYYYMMs."
    exit 1
fi

if [ "$1" = "all" ]; then
    CATEGORY=(core toolchains compiler mpi container vendor)
else
    CATEGORY=$1
fi

MODULEPATH_DEFAULT=/apps/modulefiles/standard/core:/apps/modulefiles/standard/toolchains:/apps/modulefiles/vendor

# stdout/stderr from module load
TMP=$(mktemp)


function ml {
    module purge
    module load "$@" &>$TMP
}

function print_result {
    N=$1
    Npass=$2
    shift 2
    FAIL=("$@")
    Nfail=${#FAIL[@]} 

    echo "--------"
    echo "PASS: $Npass/$N"
    echo "FAIL: $Nfail/$N"
    if [ $Nfail -gt 0 ]; then
        for i in "${FAIL[@]}"; do
            echo "  $i"
        done
    fi
}

unset MODULEPATH
export MODULEPATH=$MODULEPATH_DEFAULT

for i in ${CATEGORY[@]}; do
    if [ "$i" = "vendor" ]; then
        PREFIX=/apps/modulefiles/$i
    else
        PREFIX=/apps/modulefiles/standard/$i
    fi

# list of modules that failed to load
    FAIL=()

    echo "[$PREFIX]"
    LUAS=($(find $PREFIX -name '*.lua'))
    N=${#LUAS[@]}
    for j in ${LUAS[@]}; do
        ML=()
        LUA=$(basename $j)
        APP=$(echo $j|awk -F'/' '{print $(NF-1)}')
        VERSION=${LUA/.lua/}

        case "$i" in 
        "core"|"toolchains"|"vendor")
            ;;
        "compiler"|"container"|"mpi")
            n=$((${#PREFIX}+1))
            PARENT=$(dirname $j)
            PARENT=${PARENT:$n}
            PARENT=${PARENT%/*}
            COMPILER=${PARENT%%/*}

            if [ "$COMPILER" = "gcc-cuda" ]; then
                if [ "$i" = "mpi" ]; then
# e.g. PARENT=gcc-cuda/9.2.0-11.0.228/openmpi/3.1.6
# module load gcc/9.2.0 cuda/11.0.228 openmpi/3.1.6
                    read M12 V12 M3 V3 <<< $(echo $PARENT | sed 's/\// /g')
                    read M1 M2 <<< $(echo ${M12/-/ })
                    read V1 V2 <<< $(echo ${V12/-/ })
                    ML+=("$M1/$V1" "$M2/$V2" "$M3/$V3")
                else
                    read M12 V12 <<< $(echo ${PARENT/\// })
                    read M1 M2 <<< $(echo ${M12/-/ })
                    read V1 V2 <<< $(echo ${V12/-/ })
                    ML+=("$M1/$V1" "$M2/$V2")
                fi
            else
                if [ "$i" = "mpi" ]; then
                    ML+=($(echo $PARENT|awk -F'/' '{printf "%s/%s %s/%s",$1,$2,$3,$4}'))
                else
                    ML+=($PARENT)
                fi
            fi
            echo -n "$PARENT/"
            ;;
        *)
            echo "Unknown category"
            exit 1
            ;;
        esac

        echo -n "$APP/$VERSION "
# hidden module
        if [ ${VERSION:0:1} = "." ]; then 
            echo -n "(H) "
        fi
        echo -n "... "

        ML+=("$APP/$VERSION")
        ml "${ML[@]}"

        if [ $? -eq 0 ]; then
            echo "PASS"
        else 
            echo "FAIL"
            cat $TMP

            case "$i" in
            "core"|"toolchain")
                FAIL+=("$APP/$VERSION")
                ;;
            *)
                FAIL+=("$PARENT/$APP/$VERSION")
                ;;
            esac
        fi
    done

    Npass=$(($N-${#FAIL[@]}))
    print_result $N $Npass "${FAIL[@]}"
    echo
done

rm $TMP
