#!/bin/bash
# test module load for the entire apps stack
# Ruoshi Sun
# 2020-11-17

PREFIX=/apps/modulefiles/standard/core
TMP=$(mktemp)

function ml {
    module purge
    module load $1/$2 &>$TMP
}

function print_result {
    STATUS=$1
    shift

    if [ "$STATUS" = "Pass" ]; then
        Npass=$1
        echo "$STATUS ($Npass)"
    else
        LIST=("$@")
        Nlist=${#LIST[@]} 
        echo "$STATUS ($Nlist)"
        if [ $Nlist -gt 0 ]; then
            for i in "${LIST[@]}"; do
                echo "  $i"
            done
        fi
    fi
}

# list of modules that failed to load
FAIL=()
# list of modules that do not have a modulefile
EMPTY=()
# number of modules
N=0
Npass=0

echo "[$PREFIX]"
for APP in `ls $PREFIX`; do
    N=$((N+1))
    LUA=($(find $PREFIX/$APP -name '*.lua' -exec basename {} \;))

    if [ ${#LUA[@]} -eq 0 ]; then
        echo "$APP ... EMPTY"
        EMPTY+=("$APP")
        continue
    fi

    for VERSION in ${LUA[@]/.lua/}; do
        echo -n "$APP/$VERSION "
        if [ ${VERSION:0:1} = "." ]; then 
            echo -n "(H) "
        fi
        echo -n "... "

        ml $APP $VERSION
        if [ $? -eq 0 ]; then
            echo "PASS"
            Npass=$((Npass+1))
        else 
            echo "FAIL"
            FAIL+=("$APP/$VERSION")
            cat $TMP
        fi
    done
done

echo "########"
echo "Results"
echo "--------"
echo "Total: $N"
print_result Pass  $Npass
print_result Empty "${EMPTY[@]}"
print_result Fail  "${FAIL[@]}"
rm $TMP
