#!/bin/bash
# Remove non-modulefiles
NONMODULES=( $(find /apps/modulefiles -type f ! \( -name '*.lua' -o -name 'default' \)) )
printf "%s\n" "${NONMODULES[@]}"

read -p "== Remove? [y/N]" yn

if [[ ! $yn =~ ^[Yy]$ ]]; then
    echo "== No changes performed."
    exit 0
fi

echo "== Removing..."
rm ${NONMODULES[@]}

echo "== Done."
