#!/bin/bash
# From the EasyBuild module installation log file read the source file path and check the timestamp

DIR=/apps/software/standard

function check {
    case $1 in 
        core) d=4;;
        compiler) d=6;;
        mpi) d=8;;
    esac
    find $1 -maxdepth $d -name '*.log' -exec sh -c "f=\$(awk -F\' '/Added sources/ {print \$8}' {}) && \
    [ ! -z \"\$f\" ] && ls -l --time-style=+%Y%m%d \$f" \; | sort -nrk 6
}

cd $DIR

if [ $# -eq 1 ]; then
    check $1
    exit
fi

for i in core compiler mpi; do
    echo [$i]
    check $i
    echo
done
