#!/bin/bash
# compare two apps trees
# print results as markdown
#
# Ruoshi Sun
# 2020-02-18

module purge
ml gcc/7.1.0 tree

STACK1=201912
STACK2=202003
DIR=~/tree/$STACK2

function stack_diff {
    CATEGORY=$1
    DEPTH=$2
    TREE1=tree-${STACK1}-${CATEGORY}.txt
    TREE2=tree-${STACK2}-${CATEGORY}.txt
    TREE12=tree-${STACK1}-${STACK2}-${CATEGORY}.txt
    APPDIR1=/sfs/applications/$STACK1/software/standard
    APPDIR2=/sfs/applications/$STACK2/software/standard

    cd $APPDIR1/$CATEGORY
    tree -df -L $DEPTH . | sed 's/^.....//' > $DIR/$TREE1
    cd $APPDIR2/$CATEGORY
    tree -df -L $DEPTH . | sed 's/^.....//' > $DIR/$TREE2

    diff <(parse $DIR/$TREE1) <(parse $DIR/$TREE2) > $DIR/$TREE12

    tree2md $CATEGORY $DEPTH $TREE12
}

function parse {
    FILE=$1
    sed 's/[^0-9a-zA-Z_\-\.\/]*//g' $FILE
}

function tree2md {
    CATEGORY=$1
    DEPTH=$2
    TREE12=$3
    
    NF=$((DEPTH+1))
    LIST=list-${STACK1}-${STACK2}-${CATEGORY}.txt

# Steps:
# 1. only show deepest level directory
# 2. change to +/-
# 3. group +/-
# 4. write
    TMP=`mktemp`

    awk -F'/' -v n=$NF '{
        if (NF==n) print
    }' $DIR/$TREE12 | \
    sed -e '/^[^><]/d' \
        -e 's/^>/\+ /' \
        -e 's/^</\- /' \
    > $TMP

    grep "^+" $TMP >$DIR/$LIST
    grep "^-" $TMP >>$DIR/$LIST

# print markdown
    echo "#### $CATEGORY"
    echo "\`\`\`bash"
    cat $DIR/$LIST
    echo "\`\`\`"
    echo

# clean up
    rm $TMP
}

# core
stack_diff core       2

# compiler
stack_diff compiler   4

# mpi
stack_diff mpi        6

# toolchains
stack_diff toolchains 2

# container
stack_diff container  4
